### PR TITLE
Add toString functionality to CallableReflection

### PR DESCRIPTION
**Pull request by mwijngaard**
This should facilitate easier debugging by using it in e.g. error messages

### CODE REVIEW

**Comment by Raphhh** [comment]
Thanks a lot! :)

https://github.com/Raphhh/trex-reflection/releases/tag/1.1.0

**Comment by mwijngaard** [comment]
Thanks for the quick merge! It looks like the package is not auto updated on packagist (any more?). I guess that has something to do with with the recommended way of publishing packages having changed to using a webhook since the last release. Mind taking a look?

**Comment by Raphhh** [comment]
Packagist updated to 1.1.0. :)

**Comment by mwijngaard** [comment]
Once again, thanks a lot for the quick response!

**Pull request merged**
